'use client';
import {useMemo,useState} from 'react';
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer,CartesianGrid} from 'recharts';

type Inverter={id:string;name:string;brand:string;status:'Online'|'Atenção'|'Falha';power:number;generation:number};
type System={id:string;name:string;location:string;inverters:Inverter[]};
const seed:System[]=[
{id:'s1',name:'Residencial Jardim Europa',location:'Sorocaba - SP',inverters:[{id:'i1',name:'INV-001',brand:'Fabricante Mock A',status:'Online',power:7.8,generation:32.4},{id:'i2',name:'INV-002',brand:'Fabricante Mock B',status:'Online',power:6.2,generation:25.1}]},
{id:'s2',name:'Comercial Centro',location:'Sorocaba - SP',inverters:[{id:'i3',name:'INV-003',brand:'Fabricante Mock A',status:'Atenção',power:4.9,generation:18.7}]},
{id:'s3',name:'Chácara Horizonte',location:'Votorantim - SP',inverters:[{id:'i4',name:'INV-004',brand:'Fabricante Mock C',status:'Falha',power:0,generation:3.2}]}
];
const chart=[{hora:'06h',geracao:4},{hora:'08h',geracao:18},{hora:'10h',geracao:42},{hora:'12h',geracao:58},{hora:'14h',geracao:51},{hora:'16h',geracao:29},{hora:'18h',geracao:8}];
function Login({onLogin}:{onLogin:(role:'user'|'admin')=>void}){const [register,setRegister]=useState(false);const [email,setEmail]=useState('');return <main className="login"><section className="login-box"><div className="brand">LUX<span>.io</span></div><p className="muted">Monitoramento inteligente de sistemas fotovoltaicos.</p><h2>{register?'Criar conta':'Entrar'}</h2>{register&&<><label className="small">Nome</label><input className="form" placeholder="Seu nome" style={{width:'100%',padding:11,border:'1px solid #dbe3de',borderRadius:10}}/></>}<label className="small">E-mail</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="cliente@exemplo.com" style={{width:'100%',padding:11,border:'1px solid #dbe3de',borderRadius:10}}/><label className="small">Senha</label><input type="password" placeholder="••••••••" style={{width:'100%',padding:11,border:'1px solid #dbe3de',borderRadius:10}}/><button className="btn" style={{width:'100%',marginTop:18}} onClick={()=>onLogin(email.includes('admin')?'admin':'user')}>{register?'Cadastrar e entrar':'Entrar'}</button><button className="btn secondary" style={{width:'100%',marginTop:9}} onClick={()=>setRegister(!register)}>{register?'Já tenho uma conta':'Criar uma conta'}</button><p className="muted small" style={{marginTop:16}}>Demo: use um e-mail contendo “admin” para entrar como administrador.</p></section></main>}
export default function Home(){const [role,setRole]=useState<'user'|'admin'|null>(null);const [page,setPage]=useState('dashboard');const [systems,setSystems]=useState(seed);const [selected,setSelected]=useState<System|null>(null);const [newName,setNewName]=useState('');const totals=useMemo(()=>{const inv=systems.flatMap(s=>s.inverters);return {systems:systems.length,inverters:inv.length,gen:inv.reduce((a,i)=>a+i.generation,0),fail:inv.filter(i=>i.status==='Falha').length}},[systems]);if(!role)return <Login onLogin={setRole}/>;
const alerts=[{text:'INV-004 está em falha de comunicação.',severity:'Falha',system:'Chácara Horizonte'},{text:'INV-003 apresenta atenção no monitoramento.',severity:'Atenção',system:'Comercial Centro'}];
function addSystem(){if(!newName.trim())return;const s:System={id:Date.now().toString(),name:newName,location:'Sorocaba - SP',inverters:[{id:Date.now()+'i',name:'INV-MOCK',brand:'Fabricante Mock A',status:'Online',power:5.5,generation:21.3}]};setSystems([...systems,s]);setNewName('');setPage('systems')}
return <div className="shell"><aside className="sidebar"><div className="brand">LUX<span>.io</span></div><div className="sub">Solar intelligence platform</div><nav className="nav">{[['dashboard','Dashboard'],['systems','Sistemas'],['alerts','Alertas'],...(role==='admin'?[['admin','Administração']]:[])].map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}>{label}</button>)}</nav><button className="btn secondary" style={{width:'100%',marginTop:25}} onClick={()=>setRole(null)}>Sair</button></aside><main className="main"><div className="top"><div><h1>{page==='dashboard'?'Visão geral':page==='systems'?'Sistemas':page==='alerts'?'Alertas':'Administração'}</h1><span className="muted">Dados simulados para demonstração do MVP</span></div><span className="pill">{role==='admin'?'Administrador':'Cliente'}</span></div>
{page==='dashboard'&&<><section className="grid"><div className="card"><div className="label">Sistemas monitorados</div><div className="metric">{totals.systems}</div></div><div className="card"><div className="label">Inversores</div><div className="metric">{totals.inverters}</div></div><div className="card"><div className="label">Geração acumulada</div><div className="metric">{totals.gen.toFixed(1)} <span className="label">kWh</span></div></div><div className="card"><div className="label">Falhas ativas</div><div className="metric">{totals.fail}</div></div></section><section className="content-grid"><div className="card"><h2>Geração de energia — hoje</h2><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="hora"/><YAxis/><Tooltip/><Line type="monotone" dataKey="geracao" stroke="#1f9d55" strokeWidth={3}/></LineChart></ResponsiveContainer></div></div><div className="card"><h2>Alertas recentes</h2>{alerts.map((a,i)=><div className="alert" key={i}><strong>{a.severity}</strong><div className="small">{a.text}</div><div className="small muted">{a.system}</div></div>)}</div></section><section className="card" style={{marginTop:18}}><h2>Status dos sistemas</h2>{systems.map(s=><div className="system" key={s.id}><div><strong>{s.name}</strong><div className="small muted">{s.location} · {s.inverters.length} inversor(es)</div></div><div className={s.inverters.some(i=>i.status==='Falha')?'bad':s.inverters.some(i=>i.status==='Atenção')?'warn':'ok'}>{s.inverters.some(i=>i.status==='Falha')?'Falha':s.inverters.some(i=>i.status==='Atenção')?'Atenção':'Online'}</div></div>)}</section></>}
{page==='systems'&&<><section className="card form"><h2>Novo sistema</h2><input value={newName} onChange={e=>setNewName(e.target.value)} placeholder="Nome do sistema"/><button className="btn" style={{marginTop:10}} onClick={addSystem}>Cadastrar sistema</button></section><section className="card" style={{marginTop:18}}><h2>Sistemas cadastrados</h2>{systems.map(s=><div className="system" key={s.id}><div><strong>{s.name}</strong><div className="small muted">{s.location} · {s.inverters.length} inversor(es)</div></div><button className="btn secondary" onClick={()=>{setSelected(s);setPage('details')}}>Detalhes</button></div>)}</section></>}
{page==='details'&&selected&&<section className="card"><div className="row" style={{justifyContent:'space-between'}}><div><h2>{selected.name}</h2><span className="muted">{selected.location}</span></div><button className="btn secondary" onClick={()=>setPage('systems')}>Voltar</button></div><table className="table"><thead><tr><th>Inversor</th><th>Fabricante</th><th>Status</th><th>Potência</th><th>Geração</th></tr></thead><tbody>{selected.inverters.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.brand}</td><td className={i.status==='Falha'?'bad':i.status==='Atenção'?'warn':'ok'}>{i.status}</td><td>{i.power} kW</td><td>{i.generation} kWh</td></tr>)}</tbody></table></section>}
{page==='alerts'&&<section className="card"><h2>Central de alertas</h2>{alerts.map((a,i)=><div className="system" key={i}><div><strong>{a.text}</strong><div className="small muted">Sistema: {a.system}</div></div><span className={a.severity==='Falha'?'bad':'warn'}>{a.severity}</span></div>)}</section>}
{page==='admin'&&role==='admin'&&<section className="card"><h2>Administração</h2><p className="muted">Área demonstrativa do perfil administrador.</p><table className="table"><thead><tr><th>Indicador</th><th>Valor</th></tr></thead><tbody><tr><td>Clientes cadastrados</td><td>1 (demo)</td></tr><tr><td>Sistemas monitorados</td><td>{systems.length}</td></tr><tr><td>Fabricantes mockados</td><td>3</td></tr></tbody></table></section>}
</main></div>}
